<?php if ($this->grid->hasFilters()): ?>

    <?php
        $form = $this->filtersForm;
        $form->prepare();
        $form->setAttribute('action', $this->url(null, array('action' => 'list')));
        $form->setAttribute('method', 'get');
        $form->setAttribute('id', 'datagrid-filters-form');

        echo $this->form()->openTag($form);
    ?>

    <tr class="filters">
        <td><!--  --></td>
        <?php foreach ($this->grid as $column) : ?>
            <?php if ($column->isVisible()): ?>
            <td>
                <?php if ($this->grid->hasFilter($column->getName())): ?>
                    <?php $filter = $this->grid->getFilter($column->getName()); ?>
                    <?= $this->formElement($form->get($filter->getName())); ?>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        <?php endforeach; ?>
        <td>
            <div class="btn-group btn-group-xs pull-right">
                <button class="btn btn-default" type="submit" title="<?= $this->translate('Apply filters'); ?>">
                    <span class="glyphicon glyphicon-search glyphicon-white"></span>
                </button>
                <a class="btn btn-warning" href="<?= $this->url(null, array(), true)?>" title="<?= $this->translate('Reset filters'); ?>">
                    <span class="glyphicon glyphicon-remove glyphicon-white"></span>
                </a>
            </div>
        </td>
    </tr>
    <?= $this->form()->closeTag(); ?>
<?php endif; ?>