<?php $bulkActions = $this->gridManager->getBulkActions(); ?>

<?php if (!empty($bulkActions)): ?>
<div class="at-grid-group-actions">
    <div class="btn-group btn-group-xs">
        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
            <?= $this->translate("With selected") ?>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach($bulkActions as $action) : ?>
                <li>
                    <a onclick="DataGrid.action('')"
                       <?php if ($action->isConfirm()): ?>
                           onclick="return DataGrid.confirmAction(this, '<?= $action->getConfirmMessage() ?>')"
                       <?php endif;?>>
                       <?= $this->translate($action->getLabel()) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>