<div class="atf-grid-group-actions">
    <div class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" id="drop-bulk">
            <?php echo $this->translate("with selected") ?>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu" area-labeledby="drop-bulk">
            <?php foreach($this->gridManager->getActions() as $action) : ?>
                <?php if ($action['bulk'] == true): ?>
                    <li>
                        <a tabindex="-1" onclick="DataGrid.action('<?php echo $action['action'] ?>')"
                           <?php if (isset($action['confirm-message'])): ?>
                               onclick="return DataGrid.confirmAction(this, '<?= $action['confirm-message'] ?>')"
                           <?php endif;?>>
                           <?php echo $this->translate($action['label']) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>