<div class="row">
    <div class="span12">
        <div class="clearfix">
            <h2 class="left"><?php echo $this->translate($this->grid->getCaption()) ?></h2>
            <div class="right" style="margin-top: 15px;">
                <? if ($this->gridManager->isAllowCreate()): ?>
                    <a class="btn btn-warning" href="<?php echo $this->url(null, array('action' => 'create')) ?>">
                        <?php echo $this->translate('Create new') ?>
                    </a>
                <? endif; ?>
            </div>
        </div>

        <?php echo $this->render('at-datagrid/grid/paginator'); ?>
        <hr/>

        <div class="atf-grid">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" onclick="DataGrid.checkAll(this)"/>
                        </th>
                        <? foreach ($this->grid as $column) : ?>
                            <? if ($column->isVisible()): ?>
                                <th>
                                    <? if ($column->isSortable()): ?>
                                        <a class="sortable" href="<?php echo $this->atBaseQueryParams(array('page' => 1, 'order' => $column->getName() . '~' . $column->getOrderDirection())) ?>">
                                            <? if ($this->grid->getCurrentOrderColumnName() == $column->getName()): ?>
                                                <span class="active">
                                                    <?php echo $column->getLabel() ?>
                                                    <? if ($this->grid->getCurrentOrderDirection() == 'asc'): ?>
                                                        &uarr;
                                                    <? elseif($this->grid->getCurrentOrderDirection() == 'desc'): ?>
                                                        &darr;
                                                    <? endif; ?>
                                                </span>
                                            <? else: ?>
                                                <?php echo $column->getLabel() ?>
                                            <? endif; ?>
                                        </a>
                                    <? else: ?>
                                        <?php echo $column->getLabel() ?>
                                    <? endif; ?>
                                </th>
                            <? endif; ?>
                        <? endforeach; ?>
                        <th style="width: <?= count($this->gridManager->getButtonActions())*50+30 ?>px;"></th>
                    </tr>
                </thead>
                <tbody>

                    <?php echo $this->render('at-datagrid/grid/filters') ?>

                    <? if (count($this->data)): ?>
                        <?php echo $this->render('at-datagrid/grid/rows/list') ?>
                    <? endif ?>

                </tbody>
            </table>
            <? if (!count($this->data)): ?>
                <div><?php echo $this->translate("No items found.") ?></div>
            <? endif ?>
        </div>

        <? if (count($this->data)): ?>
            <?php echo $this->render('at-datagrid/grid/group-actions') ?>
        <? endif; ?>

        <hr/>
        <?php echo $this->render('at-datagrid/grid/paginator'); ?>
    </div>
</div>