<div class="row">
    <div class="col-md-12">
        <ul class="show-items-list clearfix pull-left">
            <li><?= $this->translate('View')?> </li>
            <li>
                <?php if ($this->grid->getItemsPerPage() == 10): ?>
                    <span class="b">10</span>
                <?php else: ?>
                    <a href="<?= $this->atBaseQueryParams(array('show_items' => 10)) ?>">10</a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($this->grid->getItemsPerPage() == 30): ?>
                    <span class="b">30</span>
                <?php else: ?>
                    <a href="<?= $this->atBaseQueryParams(array('show_items' => 30)) ?>">30</a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($this->grid->getItemsPerPage() == 50): ?>
                    <span class="b">50</span>
                <?php else: ?>
                    <a href="<?= $this->atBaseQueryParams(array('show_items' => 50)) ?>">50</a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($this->grid->getItemsPerPage() == 100): ?>
                    <span class="b">100</span>
                <?php else: ?>
                    <a href="<?= $this->atBaseQueryParams(array('show_items' => 100)) ?>">100</a>
                <?php endif; ?>
            </li>

            <li><?= $this->translate('records per page') ?></li>

            <li class="divider-vertical">|</li>
            <li><?= sprintf($this->translate('Total <span class="b">%d</span> record(s)'), $this->paginator->getTotalItemCount())?> </li>
        </ul>
        <div class="pull-right"><?= $this->paginationControl($this->paginator, null, 'at-datagrid/grid/pagination-control'); ?></div>
    </div>
</div>