<form method="post" action="#" id="datagrid-list-form">
    <?php foreach ($this->data as $row) : ?>
        <tr>
            <td>
                <input class="grid-table-checker" type="checkbox" value="<?= $row[$this->grid->getIdentifierColumnName()] ?>" id="item_id_<?= $row[$this->grid->getIdentifierColumnName()] ?>" name="items[]"/>
            </td>

            <?php foreach ($row as $name => $value) : ?>
                <?php if (isset($this->columns[$name]) && $this->columns[$name]->isVisible()): ?>
                    <td class="<?= 'col-' . $name ?>"><?= $value ?></td>
                <?php endif; ?>
            <?php endforeach; ?>

            <td>
                <div class="btn-group btn-group-xs pull-right">
                    <?php foreach($this->gridManager->getActions() as $action) : ?>
                        <?php
                            $routeParams = array_merge($action->getRouteParams(), ['id' => $row[$this->grid->getIdentifierColumnName()]]);
                            $actionUrl = $this->url($action->getRouteName(), $routeParams);
                        ?>
                        <a class="action-<?= $action->getName() ?> btn <?php if ($action->getName() == 'delete'): ?>btn-danger<?php else: ?>btn-default<?php endif;?>" href="<?= $actionUrl ?>"
                            <?php if ($action->isConfirm()): ?>
                                onclick="DataGrid.confirmAction(this, '<?= $this->translate($action->getConfirmMessage()) ?>')"
                            <?php endif;?>>
                            <span title="<?= $this->translate($action->getLabel()) ?>" class="<?= $action->getClass() ?>"></span>
                        </a>
                    <?php endforeach; ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <input type="hidden" value="" id="datagrid-list-form-action" name="bulk"/>
</form>