<form method="post" action="#" id="datagrid-list-form">
    <?php foreach ($this->data as $row) : ?>
        <tr>
            <td>
                <input class="grid-table-checker" type="checkbox" value="<?= $row[$this->grid->getIdentifierColumnName()] ?>" id="item_id_<?= $row[$this->grid->getIdentifierColumnName()] ?>" name="items[]"/>
            </td>

            <?php foreach ($row as $name => $value) : ?>
                <?php if (isset($this->columns[$name]) && $this->columns[$name]->isVisible()): ?>
                    <td class="<?= 'col-' . $name ?>"><?= $value ?></td>
                <?php endif; ?>
            <?php endforeach; ?>

            <td>
                <div class="btn-group btn-group-xs pull-right">
                    <?php foreach($this->gridManager->getActions() as $action) : ?>
                        <?= $this->rowAction($action, $row) ?>
                    <?php endforeach; ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <input type="hidden" value="" id="datagrid-list-form-action" name="bulk"/>
</form>