<?php $this->headScript()->appendFile('/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet('/css/at-datagrid/datagrid.css') ?>

<div class="row item-info">
    <div class="col-md-2 back">
        <a href="" title="<?php echo $this->translate('Back to list'); ?>">
            <i class="icon-arrow-left"></i> <?php echo $this->translate('Back to list'); ?>
        </a>
    </div>
    <div class="col-md-10 info">
    </div>
</div>

<div class="row">
    <?php echo $this->render('at-datagrid/form') ?>
</div>