<?php $this->headScript()->appendFile('/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet('/css/at-datagrid/datagrid.css') ?>

<div class="row item-info">
    <div class="span2 back">
        <a href="" title="<?= $this->translate('Back to list'); ?>">
            <i class="icon-arrow-left"></i> <?= $this->translate('Back to list'); ?>
        </a>
    </div>
    <div class="span10 info">
    </div>
</div>

<div class="row">
    <?= $this->render('at-datagrid/form') ?>
</div>