<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(null, array(), array(), true));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'datagrid-form');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal grid-form');

echo $this->form()->openTag($form);
?>

<?php foreach ($form->getElements() as $element): ?>
    <div class="form-group">
        <?php if ($element->getAttribute('type') == 'hidden'): ?>
            <?php echo $this->formHidden($element) ?>
        <?php else: ?>
            <?php
                $element->setLabelAttributes(array('class' => 'control-label col-md-4'));
                $element->setAttributes(array('class' => 'form-control'));
            ?>
            <?php echo $this->formLabel($element) ?>
            <div class="col-md-8">
                <?php echo $this->formElement($element) ?>
                <p class="help-block">
                    <?php echo $this->formElementErrors($element); ?>
                </p>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<div class="form-group">
    <div class="col-md-offset-3 col-md-9">
        <button type="submit" class="btn btn-info">Save</button>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>