<?php

$form = $this->gridManager->getForm();
$form->prepare();
$form->setAttribute('action', $this->url(null, array(), array(), true));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'datagrid-form');
$form->setAttribute('class', 'form-horizontal grid-form');

echo $this->form()->openTag($form);
?>

<?php foreach ($form->getElements() as $element): ?>
    <div class="control-group">
        <?php if ($element->getAttribute('type') == 'hidden'): ?>
            <?php echo $this->formHidden($element) ?>
        <?php else: ?>
            <?php $element->setLabelAttributes(array('class' => 'control-label')); ?>
            <?php echo $this->formLabel($element) ?>
            <div class="controls">
                <?php echo $this->formElement($element) ?>
                <p class="help-block">
                    <?php echo $this->formElementErrors($element); ?>
                </p>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<div class="form-actions">
    <button type="submit" class="btn btn-info">Save</button>
</div>

<?php echo $this->form()->closeTag(); ?>