<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(null, array(), array(), true));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'datagrid-form');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal grid-form');

echo $this->form()->openTag($form);
?>

<?php foreach ($form->getElements() as $element): ?>
        <?php if ($element->getAttribute('type') == 'hidden'): ?>
            <?php echo $this->formHidden($element) ?>
        <?php elseif ($element->getAttribute('type') != 'submit'): ?>
            <div class="form-group">
                <?php
                    $element->setLabelAttributes(array('class' => 'control-label col-md-3'));
                    $element->setAttributes(array('class' => 'form-control'));
                ?>
                <?php echo $this->formLabel($element) ?>
                <div class="col-md-9">
                    <?php echo $this->formElement($element) ?>
                    <p class="help-block">
                        <?php echo $this->formElementErrors($element); ?>
                    </p>
                </div>
            </div>
        <?php endif; ?>
<?php endforeach; ?>

<div class="form-group">
    <div class="col-md-offset-3 col-md-9">
        <?php
            $submit = $form->get('submit');
            $submit->setAttributes(array('class' => 'btn btn-info pull-right'));
        ?>
        <?php echo $this->formSubmit($submit) ?>
        <a href="<?php echo $this->backUrl ?>" title="<?php echo $this->translate('Back to list'); ?>">
            <?php echo $this->translate('Back to list'); ?>
        </a>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>