<?php $this->headScript()->appendFile('/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet('/css/at-datagrid/datagrid.css') ?>

<div class="row">
    <div class="col-md-12">
        <div class="clearfix">
            <h2 class="pull-left"><?php echo $this->translate($this->grid->getCaption()) ?></h2>
            <div class="pull-right" style="margin-top: 15px;">
                <?php if ($this->gridManager->isAllowCreate()): ?>
                    <a class="btn btn-warning" href="<?php echo $this->url(null, array('action' => 'create')) ?>">
                        <?php echo $this->translate('Create new') ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <?php echo $this->render('at-datagrid/grid/paginator'); ?>
        <hr/>

        <div class="at-grid">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" onclick="DataGrid.checkAll(this)"/>
                        </th>
                        <?php foreach ($this->grid as $column) : ?>
                            <?php if ($column->isVisible()): ?>
                                <th>
                                    <?php if ($column->isSortable()): ?>
                                        <a class="sortable" href="<?php echo $this->atBaseQueryParams(array('page' => 1, 'order' => $column->getName() . '~' . $column->getOrderDirection())) ?>">
                                            <?php if ($this->grid->getCurrentOrderColumnName() == $column->getName()): ?>
                                                <span class="active">
                                                    <?php echo $column->getLabel() ?>
                                                    <?php if ($this->grid->getCurrentOrderDirection() == 'asc'): ?>
                                                        &uarr;
                                                    <?php elseif($this->grid->getCurrentOrderDirection() == 'desc'): ?>
                                                        &darr;
                                                    <?php endif; ?>
                                                </span>
                                            <?php else: ?>
                                                <?php echo $column->getLabel() ?>
                                            <?php endif; ?>
                                        </a>
                                    <?php else: ?>
                                        <?php echo $column->getLabel() ?>
                                    <?php endif; ?>
                                </th>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <th style="width: <?php echo count($this->gridManager->getInRowActions())*50+30 ?>px;"></th>
                    </tr>
                </thead>
                <tbody>

                    <?php echo $this->render('at-datagrid/grid/filters') ?>

                    <?php if (count($this->data)): ?>
                        <?php echo $this->render('at-datagrid/grid/rows/list') ?>
                    <?php endif ?>

                </tbody>
            </table>
            <?php if (!count($this->data)): ?>
                <div><?php echo $this->translate("No items found.") ?></div>
            <?php endif ?>
        </div>

        <?php if (count($this->data)): ?>
            <?php echo $this->render('at-datagrid/grid/group-actions') ?>
        <? endif; ?>

        <hr/>
        <?php echo $this->render('at-datagrid/grid/paginator'); ?>
    </div>
</div>