<form method="post" action="#" id="datagrid-list-form">
    <?php foreach ($this->rows as $row) : ?>
        <tr>
            <td>
                <input class="grid-table-checker" type="checkbox" value="<?= $row[$this->grid->getIdentifierColumnName()] ?>" id="item_id_<?= $row[$this->grid->getIdentifierColumnName()] ?>" name="items[]"/>
            </td>

            <?php foreach ($row as $name => $value) : ?>
                <?php if (isset($this->columns[$name]) && $this->columns[$name]->isVisible()): ?>
                    <td class="<?= 'col-' . $name ?>"><?= $this->columns[$name]->render($value, $row) ?></td>
                <?php endif; ?>
            <?php endforeach; ?>

            <td>
                <div class="btn-group right">
                    <?php foreach($this->grid->getButtonActions() as $action) : ?>
                        <a class="btn btn-small" href="<?= $this->url(null, array('action' => $action['action'], 'id' => $row[$this->grid->getIdentifierColumnName()])) ?>"
                            <?php if (isset($action['confirm-message'])): ?>
                            onclick="return DataGrid.confirmAction(this, '<?= $action['confirm-message'] ?>')"
                            <?php endif;?>>
                            <i title="<?= $this->translate($action['label']) ?>" class="<?= $action['class'] ?>"></i>
                        </a>
                    <?php endforeach; ?>
                    <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php foreach($this->grid->getActions() as $action) : ?>
                            <?php if ($action['button'] == false): ?>
                            <li>
                                <a href="<?= $this->url(null, array('action' => $action['action'], 'id' => $row[$this->grid->getIdentifierColumnName()])) ?>"
                                    <?php if (isset($action['confirm-message'])): ?>
                                        onclick="return DataGrid.confirmAction(this, '<?= $action['confirm-message'] ?>')"
                                    <?php endif;?>>
                                    <?= $this->translate($action['label']) ?>
                                </a>
                            </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <input type="hidden" value="" id="datagrid-list-form-action" name="cmd"/>
</form>