<?php foreach ($elements as $element): ?>
    <?php if ($element->getAttribute('type') == 'hidden'): ?>
        <?= $this->formHidden($element) ?>
    <?php elseif ($element->getAttribute('type') == 'checkbox'): ?>
        <div class="form-group">
            <div class="col-md-9 col-sm-offset-3">
                <div class="checkbox">
                    <?php $element->setLabelAttributes(array('class' => 'control-label col-md-3')); ?>
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                </div>
                <div class="help-block">
                    <div class="text-danger"><?= $this->formElementErrors($element); ?></div>
                    <div class="text-muted"><?= $element->getOption('description'); ?></div>
                </div>
            </div>
        </div>
    <?php elseif ($element->getAttribute('type') == 'radio'): ?>
        <div class="form-group">
            <?php $element->setLabelAttributes(['class' => 'control-label col-md-3']); ?>
            <?= $this->formLabel($element) ?>
            <div class="col-md-9">
                <div class="clearfix">
                    <?php foreach ($element->getValueOptions() as $value => $label): ?>
                    <div class="radio pull-left" style="margin-right: 20px;">
                        <label>
                            <input type="radio" value="<?= $value ?>" name="<?= $element->getName()?>" <?php if ($element->getValue() == $value): ?>checked<?php endif; ?>>
                            <?= $label ?>
                        </label>
                    </div>
                    <?php endforeach; ?>
                </div>
                <div class="help-block">
                    <div class="text-danger"><?= $this->formElementErrors($element); ?></div>
                    <div class="text-muted"><?= $element->getOption('description'); ?></div>
                </div>
            </div>
        </div>
    <?php elseif ($element->getAttribute('type') == 'multi_checkbox'): ?>
        <div class="form-group">
            <?php
                $element->setLabelAttributes(['class' => 'control-label col-md-3']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-md-9">
                <?php foreach ($element->getValueOptions() as $key => $value): ?>
                    <div class="checkbox">
                        <label>
                            <input <?php if ($element->hasAttribute('class')): ?>class="<?= $element->getAttribute('class') ?>"<?php endif; ?> type="checkbox" value="<?= $key ?>" name="<?= $element->getName()?>[]" <?php if ($element->getAttribute('disabled') == 'disabled'): ?>disabled<?php endif; ?>>
                            <?= $value ?>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div class="help-block">
                    <div class="text-danger"><?= $this->formElementErrors($element); ?></div>
                    <div class="text-muted"><?= $element->getOption('description'); ?></div>
                </div>
            </div>
        </div>
    <?php elseif ($element->getAttribute('type') != 'submit'): ?>
        <div class="form-group">
            <?php
                $element->setLabelAttributes(array('class' => 'control-label col-md-3'));
                $class = 'form-control';
                if ($element->getAttribute('class')) {
                    $class .= ' ' . $element->getAttribute('class');
                }
                $element->setAttribute('class', $class);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-md-9">
                <?= $this->formElement($element) ?>
                <div class="help-block">
                    <div class="text-danger"><?= $this->formElementErrors($element); ?></div>
                    <div class="text-muted"><?= $element->getOption('description'); ?></div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>