<?php
    /** @var \Zend\Form\Form $form */
    $form->prepare();

    if ($form->getAttribute('action') == '') {
        $form->setAttribute('action', $this->url(null, [], [], true));
    }

    $form->setAttribute('method', 'post');

    if ($form->getAttribute('id') == '') {
        $form->setAttribute('id', 'at-datagrid-form');
    }

    $form->setAttribute('role', 'form');
    $form->setAttribute('class', 'form-horizontal');

    echo $this->form()->openTag($form);
?>

<div>
    <?= $this->render('at-datagrid/form/_elements.phtml', ['elements' => $form->getElements()]) ?>
</div>

<?php foreach ($form->getFieldSets() as $fieldset): ?>
    <div>
        <h4><?= $this->translate($fieldset->getLabel()); ?></h4>
        <?= $this->render('at-datagrid/form/_elements.phtml', ['elements' => $fieldset->getElements()]) ?>
    </div>
<?php endforeach; ?>

<div class="clearfix">
    <div class="pull-right">
        <?php
            $submit = $form->get('submit');
            $submit->setAttributes(['class' => 'btn btn-success']);
        ?>
        <?= $this->formSubmit($submit) ?>
    </div>
</div>


<?= $this->form()->closeTag(); ?>